# Site settings
title: Nick Harding
email: njh@well.ox.ac.uk
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hardingnj.github.io" # the base hostname & protocol for your site
twitter_username: nick_harding
github_username:  harding_nj

# Build settings
markdown: kramdown
exclude: ['*.ipynb', '*.sh', '_posts/data']

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.malariagen.net/sites/default/files/styles/140-1x1/public/content/user/image/Nick%20HARDING.png
